#!/bin/sh
#
# vrf-tools
#
# Copyright (c) 2009, 2010, 2011 David Lamparter
# please refer to the COPYING file for copying permission.

ip link add name veth0.host type veth peer name veth0.vrf
ip link set veth0.host up
ip link set veth0.vrf netns $VRF_PID

